// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcvlzigenarahcxvzmuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdmx6aWdlbmFyYWhjeHZ6bXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDk0NjEsImV4cCI6MjA1OTIyNTQ2MX0.6BWSjoTuKXHpk1JXDC-ulxCc19XWXMGfC0uRT_SvmlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);